spring:
  cache:
    type: redis
    redis:
      time-to-live: 300s
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}
